{application,mailang,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{mailang_app,[]}},
              {env,[]},
              {modules,[fetch,mailang_app,mailang_sup,mailconnector,
                        refactored_fetch,rfc2047]}]}.
